### ISSUE TITLE
Check login request body

### ISSUE THREAD

**Issue by danielgara** [PacktPublishing/Deno-Web-Development#4]
https://github.com/PacktPublishing/Deno-Web-Development/blob/42265eb10aeac7111a8d3e60debc3ca7c1fb0c7c/Chapter06/sections/2-adding-authentication/museums-api/src/web/index.ts#L74

Dear Alexandre santos @asantos00. Please check the previous line.

`
const { username, password } = await ctx.request.body().value;
` 

I was not able to execute the login in your book, because it was a little different than the _register request body value_.
I think it should be something like this:

`
const { username, password } = await ctx.request.body({ type: "json" }).value;
` 

Once I modified that line, login worked. I used postman to make a test.

**Comment by asantos00** [comment]
Hi @danielgara,

Thank you so much for taking the time to note that.

It should be fixed on the next chapters and I'll quickly update the code you mentioned today!

Let me know if you have further questions.

Alexandre
